spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketbookingsystem
    username: ticketsysusr
    password: ticketsysusr
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
